.travis.yml
mix.exs

Elixir 1.4 has been out for ages, and we're about to make a large breaking change with support for Kubernetes 1.7, so this seems as good a time as any.
Also updated the versions we run against on travis.

Drop Elixir 1.3 support

---

lib/kazan/client.ex
lib/kazan/server.ex

This disables TLS verification - useful during development if using
unsigned certificates.

Add support for `insecure-skip-tls-verify`.

---

lib/kazan/server.ex

This was originally done as part of #2 - but I've moved it out into it's own PR to decouple from any kubernetes upgrade work.

Add in-cluster service account authentication.

---

.travis.yml
lib/kazan/codegen/models.ex

Also update some old Elixir versions & OTP versions.
Had to stop using String.Casing.titlecase_once as part of this, as it's
API has changed.  Just doing the same thing manually now.

Add Elixir 1.6.0 to Travis

---

CHANGELOG.md
README.md
lib/kazan.ex
lib/kazan/apis.ex
lib/kazan/codegen/apis.ex
lib/kazan/codegen/apis/api_id.ex
lib/kazan/codegen/apis/operation.ex
lib/kazan/codegen/models.ex
lib/kazan/models.ex
test/apis_test.exs
test/codegen/apis_test.exs
test/codegen/models_test.exs
test/integration_test.exs
test/kazan/client_test.exs
test/kazan/request_test.exs
test/models_test.exs

- API modules now have a `.` between their group & version names.
- Models now live under their associated API module where possible.

Reorganise API & Model modules

---

CHANGELOG.md
README.md
lib/kazan.ex
lib/kazan/apis.ex
lib/kazan/client.ex
lib/kazan/client/imp.ex
lib/kazan/codegen/apis.ex
lib/kazan/request.ex
test/integration_test.exs
test/kazan/client_imp_test.exs

`Kazan` only really has one job - talking to kubernetes.  It doesn't make much
sense for the primary function for talking to kubernetes to be hidden inside
`Kazan.Client` while the `Kazan` module goes unused.
So, this commit deprecates `Kazan.Client` and presents the `Kazan.run` &
`Kazan.run!` functions as alternatives.

Add `Kazan.run` function, deprecate `Kazan.Client`

---

lib/kazan/client/imp.ex
test/integration_test.exs
test/kazan/client_imp_test.exs

Resolves #29 
The content-type header capitalisation is also fixed in `client_imp_test.exs` as K8S returns `Content-Type` and not `content-type`.

Handle non-json responses

---

lib/kazan/server.ex

Resolves #25 
The merge request updates the `in_cluster` function to work with Kubernetes 1.7+ which changes `ca.key` name for TLS cert.
The newer version also provide env var with the internal IP address and port for the API server so you can connect to them without a proxy server. The url has been changed to use these env var instead.

Change `in_cluster` data struct

---

CHANGELOG.md
lib/kazan/client/imp.ex

So we get better error messages if someone passes the output from a
non-bang function straight into these.

Add pattern matches to `Kazan.run`

---

README.md

This change corrects the indentation of the installation and configuration instructions, adds brackets to implicit function calls such that they'd satisfy `mix format`, and fixes a module name in the example usage.

Assorted README.md fixes

---

CHANGELOG.md
README.md
lib/kazan/client/imp.ex
lib/kazan/server.ex
test/kazan/server_test.exs

The documentation for Kazan says that we support specifying a server map
in the mix config.  This was true, but the auth map within the config
was not being converted to one of the `Kazan.Server.*` structs. This
meant that the `Kazan.run` calls would fail as they pattern match on the
struct type.
This updates `Kazan.Server` with a function that properly converts maps
to the appropriate nested structs, which should allow people to specify
the auth details in their mix config.
Fixes #39

Support for specifying auth directly in mix config

---

lib/kazan/server.ex
mix.exs

YamlElixir 2.0 is functionally identical to 1.3, except for the [breaking API change](https://github.com/KamilLelonek/yaml-elixir/pull/24#pullrequestreview-109019520) which was initially introduced in 1.4. Updating the version constraint to 2.0 allows us to remove the 1.3/1.4 negotiation hack.
Sorry again for the breaking change. My fault for thinking I had internalised SemVer rules!

Use YamlElixir 2.0

---

mix.exs

The newest release of Plug [extracted the cowboy adapter](https://github.com/elixir-plug/plug/blob/7b83496207eff567ec72d91d7e9c5e1eaaa2f013/CHANGELOG.md#enhancements) into a [separate project](https://github.com/elixir-plug/plug_cowboy). Getting the tests to run now requires either using `plug_cowboy` or pinning `plug` to < 1.7.0. Otherwise there are a bunch of failures similar to:
```
warning: please add the following dependency to your mix.exs:
{:plug_cowboy, "~> 1.0"}
This dependency is required by Plug.Adapters.Cowboy
which you may be using directly or indirectly.
Note you no longer need to depend on :cowboy directly.
(plug) lib/plug/adapters/cowboy.ex:44: Plug.Adapters.Cowboy.warn_and_raise/0
(plug) lib/plug/adapters/cowboy.ex:11: Plug.Adapters.Cowboy.http/3
(bypass) …
```

Update test dependencies for Plug v1.7.0

---

lib/kazan/watcher.ex

If the parent fails due to a crash (which can be caused by the watcher crashing), then this makes the situation worse as the term cannot be logged.

Fix bug inspecting DOWN reason in watcher

---

CHANGELOG.md
config/config.exs
lib/kazan/apis.ex
lib/kazan/codegen/apis.ex
lib/kazan/codegen/models.ex
lib/kazan/codegen/naming.ex
lib/kazan/config.ex
lib/kazan/errors.ex
lib/kazan/models.ex
lib/kazan/request.ex
mix.exs
test/models_test.exs

Some users of Kazan are using k8s extensions that add new APIs & models
to k8s.  Currently the only way to get Kazan to know about these new
APIs and models is to fork the library and update the swagger
appropriately.
This commit updates kazan with two new configuration options:
- `oai_spec` allows the user to provide a different open API spec file
to compile the library with.
- `oai_name_mappings` allows the user to add extra mappings from open
api specification names to elixir modules.
Fixes #54

Allow users to provide their own OAI specs.

---

lib/kazan/client/imp.ex
lib/kazan/server.ex
lib/kazan/server/basic_auth.ex

Im trying to get kazan working with k3s (https://k3s.io/) released by Rancher. After starting the k3s server, kube config looks like this
```
apiVersion: v1
clusters:
- cluster:
certificate-authority-data: <<encoded-certificate-data>>
server: https://localhost:6443
name: default
contexts:
- context:
cluster: default
user: default
name: default
current-context: default
kind: Config
preferences: {}
users:
- name: default
user:
password: randomized-password
username: admin
```
None of the existing server auth methods support `username/password` authentication ie basic authentication strategy. This PR implements that. Tested with k3s and works fine!

implement basic auth when username and password are given

---

.formatter.exs
CHANGELOG.md
README.md
config/config.exs
lib/kazan/apis.ex
lib/kazan/client/imp.ex
lib/kazan/codegen/apis.ex
lib/kazan/codegen/apis/operation.ex
lib/kazan/codegen/models.ex
lib/kazan/codegen/naming.ex
lib/kazan/model.ex
lib/kazan/models.ex
lib/kazan/models/model_desc.ex
lib/kazan/models/property_desc.ex
lib/kazan/models/resource_id.ex
lib/kazan/request.ex
lib/kazan/server.ex
lib/kazan/server/server_info.ex
lib/kazan/watcher.ex
mix.exs
test/integration_test.exs
test/model_test.exs
test/models_test.exs
test/support/fooresource.ex

This updates Kazan with support for custom resources.  See the `Kazan.Model` documentation for more details.
Fixes #59

Add support for decoding & encoding custom resources

---

lib/kazan/request.ex

This field useful to be able to instrument the calls to Kazan.  
Do do this we have a wrapper around `Kazan.run` where we time each request and then group them by `operation_id`.

Add operation_id to %Request{}

---

mix.exs

Due to edgurgel/httpoison#375 if you use HTTPoison < v1.6.1 you will have a process leak when using watches whenever a GONE event is received from K8S.
Fixes https://github.com/obmarg/kazan/issues/73
PR also includes some formatting fixes

Upgrade httpoison to fix process leak

---

lib/kazan/codegen/models.ex

When generating the typespecs for models, the `required` field in the swagger definition is ignored, leading to dialyzer errors when instantiating a model struct without specifying all fields.
The AST previously created a typespec for a struct field like
```
my_field: my_type
``` 
but this PR now creates it as follows if the field is not required:
```
my_field: my_type | nil
```

Fix typespecs for optional model fields

---

CHANGELOG.md
lib/kazan/client/imp.ex

We now specify `[verify: :verify_peer]` when the `cacerts` SSL option is specified; this removes the warning log from `:ssl`.

Remove :ssl warning log by specifying the :verify option
